services:
  terminusdb-server:
    image: terminusdb/terminusdb-server:latest
    container_name: terminusdb-service
    restart: unless-stopped

    ports:
      - "6363:6363"

    env_file:
      - path: .env.starter
        required: true

      - path: .env
        required: false

    volumes:
      - ./data:/app/terminusdb/data
